package ar.com.agromayor.portal.db;

// Generated Jan 6, 2010 2:16:28 PM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * PortalUsuarios generated by hbm2java
 */
@Entity
@Table(name = "PORTAL_USUARIOS")
public class PortalUsuarios implements java.io.Serializable {
	private static final long serialVersionUID = 7495348192506183515L;

	private int usrCodigo;
	private String usrNombre;
	private String usrApellido;
	private String usrPass;
	private String usrMail;

	public PortalUsuarios() {
	}

	public PortalUsuarios(int usrCodigo) {
		this.usrCodigo = usrCodigo;
	}

	public PortalUsuarios(int usrCodigo, String usrNombre, String usrApellido,
			String usrPass, String usrMail) {
		this.usrCodigo = usrCodigo;
		this.usrNombre = usrNombre;
		this.usrApellido = usrApellido;
		this.usrPass = usrPass;
		this.usrMail = usrMail;
	}

	@Id
	@Column(name = "USR_CODIGO", unique = true, nullable = false, precision = 8, scale = 0)
	public int getUsrCodigo() {
		return this.usrCodigo;
	}

	public void setUsrCodigo(int usrCodigo) {
		this.usrCodigo = usrCodigo;
	}

	@Column(name = "USR_NOMBRE", length = 50)
	public String getUsrNombre() {
		return this.usrNombre;
	}

	public void setUsrNombre(String usrNombre) {
		this.usrNombre = usrNombre;
	}

	@Column(name = "USR_APELLIDO", length = 50)
	public String getUsrApellido() {
		return this.usrApellido;
	}

	public void setUsrApellido(String usrApellido) {
		this.usrApellido = usrApellido;
	}

	@Column(name = "USR_PASS", length = 20)
	public String getUsrPass() {
		return this.usrPass;
	}

	public void setUsrPass(String usrPass) {
		this.usrPass = usrPass;
	}

	@Column(name = "USR_MAIL", length = 50)
	public String getUsrMail() {
		return this.usrMail;
	}

	public void setUsrMail(String usrMail) {
		this.usrMail = usrMail;
	}

}
