package ar.com.agromayor.DB.factura;

// Generated Dec 18, 2009 1:30:23 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacturaItemsId generated by hbm2java
 */
@Embeddable
public class FacturaItemsId implements java.io.Serializable {
	private static final long serialVersionUID = 2057804358936588225L;
	
	private long cabNroInterno;
	private short detNumeroItm;

	public FacturaItemsId() {
	}

	public FacturaItemsId(long cabNroInterno, short detNumeroItm) {
		this.cabNroInterno = cabNroInterno;
		this.detNumeroItm = detNumeroItm;
	}

	@Column(name = "CAB_NRO_INTERNO", nullable = false, precision = 10, scale = 0)
	public long getCabNroInterno() {
		return this.cabNroInterno;
	}

	public void setCabNroInterno(long cabNroInterno) {
		this.cabNroInterno = cabNroInterno;
	}

	@Column(name = "DET_NUMERO_ITM", nullable = false, precision = 3, scale = 0)
	public short getDetNumeroItm() {
		return this.detNumeroItm;
	}

	public void setDetNumeroItm(short detNumeroItm) {
		this.detNumeroItm = detNumeroItm;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacturaItemsId))
			return false;
		FacturaItemsId castOther = (FacturaItemsId) other;

		return (this.getCabNroInterno() == castOther.getCabNroInterno())
				&& (this.getDetNumeroItm() == castOther.getDetNumeroItm());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (int) this.getCabNroInterno();
		result = 37 * result + this.getDetNumeroItm();
		return result;
	}

}
