package ar.com.agromayor.DB.factura;

// Generated Dec 18, 2009 1:30:23 AM by Hibernate Tools 3.2.4.GA

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * FacturaReceptorId generated by hbm2java
 */
@Embeddable
public class FacturaReceptorId implements java.io.Serializable {
	private static final long serialVersionUID = 3833480449594345528L;
	
	private short recSubcuenta;
	private int recCodigo;

	public FacturaReceptorId() {
	}

	public FacturaReceptorId(short recSubcuenta, int recCodigo) {
		this.recSubcuenta = recSubcuenta;
		this.recCodigo = recCodigo;
	}

	@Column(name = "REC_SUBCUENTA", nullable = false, precision = 3, scale = 0)
	public short getRecSubcuenta() {
		return this.recSubcuenta;
	}

	public void setRecSubcuenta(short recSubcuenta) {
		this.recSubcuenta = recSubcuenta;
	}

	@Column(name = "REC_CODIGO", nullable = false, precision = 8, scale = 0)
	public int getRecCodigo() {
		return this.recCodigo;
	}

	public void setRecCodigo(int recCodigo) {
		this.recCodigo = recCodigo;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof FacturaReceptorId))
			return false;
		FacturaReceptorId castOther = (FacturaReceptorId) other;

		return (this.getRecSubcuenta() == castOther.getRecSubcuenta())
				&& (this.getRecCodigo() == castOther.getRecCodigo());
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + this.getRecSubcuenta();
		result = 37 * result + this.getRecCodigo();
		return result;
	}

}
