package ar.com.agromayor.DB.factura;

// Generated Dec 18, 2009 1:30:23 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FacturaEmisor generated by hbm2java
 */
@Entity
@Table(name = "FACTURA_EMISOR")
public class FacturaEmisor implements java.io.Serializable {
	private static final long serialVersionUID = 5852621981555501133L;
	
	private byte emiCodigo;
	private String emiNombre;
	private String emiCalle;
	private String emiCodPostal;
	private String emiCodTipoResp;
	private String emiCodVendedor;
	private String emiCuit;
	private String emiDepto;
	private String emiTipoResp;
	private Date emiInicioAct;
	private String emiLocalidad;
	private String emiMunicipio;
	private String emiNombreVendedor;
	private String emiNroIibb;
	private Long emiNumero;
	private String emiPais;
	private Long emiPiso;
	private String emiProvincia;
	private String emiRefetencia;
	private String emiLogoMediano;
	private String emiLogoChico;
	private String emiDireccionWeb;
	private String emiTelefono;
	private Set<FacturaCabecera> facturaCabeceras = new HashSet<FacturaCabecera>(
			0);

	public FacturaEmisor() {
	}

	public FacturaEmisor(byte emiCodigo) {
		this.emiCodigo = emiCodigo;
	}

	public FacturaEmisor(byte emiCodigo, String emiNombre, String emiCalle,
			String emiCodPostal, String emiCodTipoResp, String emiCodVendedor,
			String emiCuit, String emiDepto, String emiTipoResp,
			Date emiInicioAct, String emiLocalidad, String emiMunicipio,
			String emiNombreVendedor, String emiNroIibb, Long emiNumero,
			String emiPais, Long emiPiso, String emiProvincia,
			String emiRefetencia, String emiLogoMediano, String emiLogoChico,
			String emiDireccionWeb, String emiTelefono,
			Set<FacturaCabecera> facturaCabeceras) {
		this.emiCodigo = emiCodigo;
		this.emiNombre = emiNombre;
		this.emiCalle = emiCalle;
		this.emiCodPostal = emiCodPostal;
		this.emiCodTipoResp = emiCodTipoResp;
		this.emiCodVendedor = emiCodVendedor;
		this.emiCuit = emiCuit;
		this.emiDepto = emiDepto;
		this.emiTipoResp = emiTipoResp;
		this.emiInicioAct = emiInicioAct;
		this.emiLocalidad = emiLocalidad;
		this.emiMunicipio = emiMunicipio;
		this.emiNombreVendedor = emiNombreVendedor;
		this.emiNroIibb = emiNroIibb;
		this.emiNumero = emiNumero;
		this.emiPais = emiPais;
		this.emiPiso = emiPiso;
		this.emiProvincia = emiProvincia;
		this.emiRefetencia = emiRefetencia;
		this.emiLogoMediano = emiLogoMediano;
		this.emiLogoChico = emiLogoChico;
		this.emiDireccionWeb = emiDireccionWeb;
		this.emiTelefono = emiTelefono;
		this.facturaCabeceras = facturaCabeceras;
	}

	@Id
	@Column(name = "EMI_CODIGO", unique = true, nullable = false, precision = 2, scale = 0)
	public byte getEmiCodigo() {
		return this.emiCodigo;
	}

	public void setEmiCodigo(byte emiCodigo) {
		this.emiCodigo = emiCodigo;
	}

	@Column(name = "EMI_NOMBRE", length = 50)
	public String getEmiNombre() {
		return this.emiNombre;
	}

	public void setEmiNombre(String emiNombre) {
		this.emiNombre = emiNombre;
	}

	@Column(name = "EMI_CALLE", length = 40)
	public String getEmiCalle() {
		return this.emiCalle;
	}

	public void setEmiCalle(String emiCalle) {
		this.emiCalle = emiCalle;
	}

	@Column(name = "EMI_COD_POSTAL", length = 15)
	public String getEmiCodPostal() {
		return this.emiCodPostal;
	}

	public void setEmiCodPostal(String emiCodPostal) {
		this.emiCodPostal = emiCodPostal;
	}

	@Column(name = "EMI_COD_TIPO_RESP", length = 2)
	public String getEmiCodTipoResp() {
		return this.emiCodTipoResp;
	}

	public void setEmiCodTipoResp(String emiCodTipoResp) {
		this.emiCodTipoResp = emiCodTipoResp;
	}

	@Column(name = "EMI_COD_VENDEDOR", length = 5)
	public String getEmiCodVendedor() {
		return this.emiCodVendedor;
	}

	public void setEmiCodVendedor(String emiCodVendedor) {
		this.emiCodVendedor = emiCodVendedor;
	}

	@Column(name = "EMI_CUIT", length = 15)
	public String getEmiCuit() {
		return this.emiCuit;
	}

	public void setEmiCuit(String emiCuit) {
		this.emiCuit = emiCuit;
	}

	@Column(name = "EMI_DEPTO", length = 5)
	public String getEmiDepto() {
		return this.emiDepto;
	}

	public void setEmiDepto(String emiDepto) {
		this.emiDepto = emiDepto;
	}

	@Column(name = "EMI_TIPO_RESP", length = 35)
	public String getEmiTipoResp() {
		return this.emiTipoResp;
	}

	public void setEmiTipoResp(String emiTipoResp) {
		this.emiTipoResp = emiTipoResp;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "EMI_INICIO_ACT", length = 7)
	public Date getEmiInicioAct() {
		return this.emiInicioAct;
	}

	public void setEmiInicioAct(Date emiInicioAct) {
		this.emiInicioAct = emiInicioAct;
	}

	@Column(name = "EMI_LOCALIDAD", length = 40)
	public String getEmiLocalidad() {
		return this.emiLocalidad;
	}

	public void setEmiLocalidad(String emiLocalidad) {
		this.emiLocalidad = emiLocalidad;
	}

	@Column(name = "EMI_MUNICIPIO", length = 40)
	public String getEmiMunicipio() {
		return this.emiMunicipio;
	}

	public void setEmiMunicipio(String emiMunicipio) {
		this.emiMunicipio = emiMunicipio;
	}

	@Column(name = "EMI_NOMBRE_VENDEDOR", length = 35)
	public String getEmiNombreVendedor() {
		return this.emiNombreVendedor;
	}

	public void setEmiNombreVendedor(String emiNombreVendedor) {
		this.emiNombreVendedor = emiNombreVendedor;
	}

	@Column(name = "EMI_NRO_IIBB", length = 15)
	public String getEmiNroIibb() {
		return this.emiNroIibb;
	}

	public void setEmiNroIibb(String emiNroIibb) {
		this.emiNroIibb = emiNroIibb;
	}

	@Column(name = "EMI_NUMERO", precision = 10, scale = 0)
	public Long getEmiNumero() {
		return this.emiNumero;
	}

	public void setEmiNumero(Long emiNumero) {
		this.emiNumero = emiNumero;
	}

	@Column(name = "EMI_PAIS", length = 25)
	public String getEmiPais() {
		return this.emiPais;
	}

	public void setEmiPais(String emiPais) {
		this.emiPais = emiPais;
	}

	@Column(name = "EMI_PISO", precision = 10, scale = 0)
	public Long getEmiPiso() {
		return this.emiPiso;
	}

	public void setEmiPiso(Long emiPiso) {
		this.emiPiso = emiPiso;
	}

	@Column(name = "EMI_PROVINCIA", length = 25)
	public String getEmiProvincia() {
		return this.emiProvincia;
	}

	public void setEmiProvincia(String emiProvincia) {
		this.emiProvincia = emiProvincia;
	}

	@Column(name = "EMI_REFETENCIA", length = 15)
	public String getEmiRefetencia() {
		return this.emiRefetencia;
	}

	public void setEmiRefetencia(String emiRefetencia) {
		this.emiRefetencia = emiRefetencia;
	}

	@Column(name = "EMI_LOGO_MEDIANO", length = 200)
	public String getEmiLogoMediano() {
		return this.emiLogoMediano;
	}

	public void setEmiLogoMediano(String emiLogoMediano) {
		this.emiLogoMediano = emiLogoMediano;
	}

	@Column(name = "EMI_LOGO_CHICO", length = 200)
	public String getEmiLogoChico() {
		return this.emiLogoChico;
	}

	public void setEmiLogoChico(String emiLogoChico) {
		this.emiLogoChico = emiLogoChico;
	}

	@Column(name = "EMI_DIRECCION_WEB", length = 100)
	public String getEmiDireccionWeb() {
		return this.emiDireccionWeb;
	}

	public void setEmiDireccionWeb(String emiDireccionWeb) {
		this.emiDireccionWeb = emiDireccionWeb;
	}

	@Column(name = "EMI_TELEFONO", length = 50)
	public String getEmiTelefono() {
		return this.emiTelefono;
	}

	public void setEmiTelefono(String emiTelefono) {
		this.emiTelefono = emiTelefono;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facturaEmisor")
	public Set<FacturaCabecera> getFacturaCabeceras() {
		return this.facturaCabeceras;
	}

	public void setFacturaCabeceras(Set<FacturaCabecera> facturaCabeceras) {
		this.facturaCabeceras = facturaCabeceras;
	}

}
