package ar.com.agromayor.DB.factura;

// Generated Dec 18, 2009 1:30:23 AM by Hibernate Tools 3.2.4.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FacturaReceptor generated by hbm2java
 */
@Entity
@Table(name = "FACTURA_RECEPTOR")
public class FacturaReceptor implements java.io.Serializable {
	private static final long serialVersionUID = 1873831340583431912L;
	
	private FacturaReceptorId id;
	private String recCalle;
	private String recCodPostal;
	private String recCodComprador;
	private String recTipoResp;
	private String recCondIibb;
	private String recDepto;
	private Date recInicioAct;
	private String recLocalidad;
	private String recMunicipio;
	private String recNombre;
	private String recNombreComprador;
	private String recNroDoc;
	private String recNroIibb;
	private Long recNumero;
	private String recPais;
	private String recPiso;
	private String recProvincia;
	private String recReferencia;
	private String recTipoDoc;
	private Set<FacturaCabecera> facturaCabeceras = new HashSet<FacturaCabecera>(
			0);

	public FacturaReceptor() {
	}

	public FacturaReceptor(FacturaReceptorId id) {
		this.id = id;
	}

	public FacturaReceptor(FacturaReceptorId id, String recCalle,
			String recCodPostal, String recCodComprador, String recTipoResp,
			String recCondIibb, String recDepto, Date recInicioAct,
			String recLocalidad, String recMunicipio, String recNombre,
			String recNombreComprador, String recNroDoc, String recNroIibb,
			Long recNumero, String recPais, String recPiso,
			String recProvincia, String recReferencia, String recTipoDoc,
			Set<FacturaCabecera> facturaCabeceras) {
		this.id = id;
		this.recCalle = recCalle;
		this.recCodPostal = recCodPostal;
		this.recCodComprador = recCodComprador;
		this.recTipoResp = recTipoResp;
		this.recCondIibb = recCondIibb;
		this.recDepto = recDepto;
		this.recInicioAct = recInicioAct;
		this.recLocalidad = recLocalidad;
		this.recMunicipio = recMunicipio;
		this.recNombre = recNombre;
		this.recNombreComprador = recNombreComprador;
		this.recNroDoc = recNroDoc;
		this.recNroIibb = recNroIibb;
		this.recNumero = recNumero;
		this.recPais = recPais;
		this.recPiso = recPiso;
		this.recProvincia = recProvincia;
		this.recReferencia = recReferencia;
		this.recTipoDoc = recTipoDoc;
		this.facturaCabeceras = facturaCabeceras;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "recSubcuenta", column = @Column(name = "REC_SUBCUENTA", nullable = false, precision = 3, scale = 0)),
			@AttributeOverride(name = "recCodigo", column = @Column(name = "REC_CODIGO", nullable = false, precision = 8, scale = 0)) })
	public FacturaReceptorId getId() {
		return this.id;
	}

	public void setId(FacturaReceptorId id) {
		this.id = id;
	}

	@Column(name = "REC_CALLE", length = 40)
	public String getRecCalle() {
		return this.recCalle;
	}

	public void setRecCalle(String recCalle) {
		this.recCalle = recCalle;
	}

	@Column(name = "REC_COD_POSTAL", length = 8)
	public String getRecCodPostal() {
		return this.recCodPostal;
	}

	public void setRecCodPostal(String recCodPostal) {
		this.recCodPostal = recCodPostal;
	}

	@Column(name = "REC_COD_COMPRADOR", length = 15)
	public String getRecCodComprador() {
		return this.recCodComprador;
	}

	public void setRecCodComprador(String recCodComprador) {
		this.recCodComprador = recCodComprador;
	}

	@Column(name = "REC_TIPO_RESP", length = 35)
	public String getRecTipoResp() {
		return this.recTipoResp;
	}

	public void setRecTipoResp(String recTipoResp) {
		this.recTipoResp = recTipoResp;
	}

	@Column(name = "REC_COND_IIBB", length = 25)
	public String getRecCondIibb() {
		return this.recCondIibb;
	}

	public void setRecCondIibb(String recCondIibb) {
		this.recCondIibb = recCondIibb;
	}

	@Column(name = "REC_DEPTO", length = 5)
	public String getRecDepto() {
		return this.recDepto;
	}

	public void setRecDepto(String recDepto) {
		this.recDepto = recDepto;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "REC_INICIO_ACT", length = 7)
	public Date getRecInicioAct() {
		return this.recInicioAct;
	}

	public void setRecInicioAct(Date recInicioAct) {
		this.recInicioAct = recInicioAct;
	}

	@Column(name = "REC_LOCALIDAD", length = 40)
	public String getRecLocalidad() {
		return this.recLocalidad;
	}

	public void setRecLocalidad(String recLocalidad) {
		this.recLocalidad = recLocalidad;
	}

	@Column(name = "REC_MUNICIPIO", length = 40)
	public String getRecMunicipio() {
		return this.recMunicipio;
	}

	public void setRecMunicipio(String recMunicipio) {
		this.recMunicipio = recMunicipio;
	}

	@Column(name = "REC_NOMBRE", length = 80)
	public String getRecNombre() {
		return this.recNombre;
	}

	public void setRecNombre(String recNombre) {
		this.recNombre = recNombre;
	}

	@Column(name = "REC_NOMBRE_COMPRADOR", length = 35)
	public String getRecNombreComprador() {
		return this.recNombreComprador;
	}

	public void setRecNombreComprador(String recNombreComprador) {
		this.recNombreComprador = recNombreComprador;
	}

	@Column(name = "REC_NRO_DOC", length = 15)
	public String getRecNroDoc() {
		return this.recNroDoc;
	}

	public void setRecNroDoc(String recNroDoc) {
		this.recNroDoc = recNroDoc;
	}

	@Column(name = "REC_NRO_IIBB", length = 15)
	public String getRecNroIibb() {
		return this.recNroIibb;
	}

	public void setRecNroIibb(String recNroIibb) {
		this.recNroIibb = recNroIibb;
	}

	@Column(name = "REC_NUMERO", precision = 10, scale = 0)
	public Long getRecNumero() {
		return this.recNumero;
	}

	public void setRecNumero(Long recNumero) {
		this.recNumero = recNumero;
	}

	@Column(name = "REC_PAIS", length = 40)
	public String getRecPais() {
		return this.recPais;
	}

	public void setRecPais(String recPais) {
		this.recPais = recPais;
	}

	@Column(name = "REC_PISO", length = 5)
	public String getRecPiso() {
		return this.recPiso;
	}

	public void setRecPiso(String recPiso) {
		this.recPiso = recPiso;
	}

	@Column(name = "REC_PROVINCIA", length = 40)
	public String getRecProvincia() {
		return this.recProvincia;
	}

	public void setRecProvincia(String recProvincia) {
		this.recProvincia = recProvincia;
	}

	@Column(name = "REC_REFERENCIA", length = 25)
	public String getRecReferencia() {
		return this.recReferencia;
	}

	public void setRecReferencia(String recReferencia) {
		this.recReferencia = recReferencia;
	}

	@Column(name = "REC_TIPO_DOC", length = 2)
	public String getRecTipoDoc() {
		return this.recTipoDoc;
	}

	public void setRecTipoDoc(String recTipoDoc) {
		this.recTipoDoc = recTipoDoc;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "facturaReceptor")
	public Set<FacturaCabecera> getFacturaCabeceras() {
		return this.facturaCabeceras;
	}

	public void setFacturaCabeceras(Set<FacturaCabecera> facturaCabeceras) {
		this.facturaCabeceras = facturaCabeceras;
	}

}
