package ar.com.agromayor.DB.factura;

// Generated Dec 18, 2009 1:30:23 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * FacturaTotales generated by hbm2java
 */
@Entity
@Table(name = "FACTURA_TOTALES")
public class FacturaTotales implements java.io.Serializable {
	private static final long serialVersionUID = 8132972879594301718L;
	private long cabNroInterno;
	private FacturaCabecera facturaCabecera;
	private BigDecimal totAlicuota;
	private BigDecimal totDescuento;
	private BigDecimal totExento;
	private BigDecimal totImpLiquidado;
	private BigDecimal totImpRni;
	private BigDecimal totImpInternos;
	private BigDecimal totMontoIva;
	private BigDecimal totNetoGravado;
	private BigDecimal totOtros;
	private BigDecimal totPercAlicIibb;
	private BigDecimal totPercImporteIibb;
	private String totPercProvPerc;
	private BigDecimal totPercepMunicipal;
	private BigDecimal totPercepciones;
	private BigDecimal totTotal;
	private BigDecimal totValorPagar;

	public FacturaTotales() {
	}

	public FacturaTotales(FacturaCabecera facturaCabecera) {
		this.facturaCabecera = facturaCabecera;
	}

	public FacturaTotales(FacturaCabecera facturaCabecera,
			BigDecimal totAlicuota, BigDecimal totDescuento,
			BigDecimal totExento, BigDecimal totImpLiquidado,
			BigDecimal totImpRni, BigDecimal totImpInternos,
			BigDecimal totMontoIva, BigDecimal totNetoGravado,
			BigDecimal totOtros, BigDecimal totPercAlicIibb,
			BigDecimal totPercImporteIibb, String totPercProvPerc,
			BigDecimal totPercepMunicipal, BigDecimal totPercepciones,
			BigDecimal totTotal, BigDecimal totValorPagar) {
		this.facturaCabecera = facturaCabecera;
		this.totAlicuota = totAlicuota;
		this.totDescuento = totDescuento;
		this.totExento = totExento;
		this.totImpLiquidado = totImpLiquidado;
		this.totImpRni = totImpRni;
		this.totImpInternos = totImpInternos;
		this.totMontoIva = totMontoIva;
		this.totNetoGravado = totNetoGravado;
		this.totOtros = totOtros;
		this.totPercAlicIibb = totPercAlicIibb;
		this.totPercImporteIibb = totPercImporteIibb;
		this.totPercProvPerc = totPercProvPerc;
		this.totPercepMunicipal = totPercepMunicipal;
		this.totPercepciones = totPercepciones;
		this.totTotal = totTotal;
		this.totValorPagar = totValorPagar;
	}

	@GenericGenerator(name = "generator", strategy = "foreign", parameters = @Parameter(name = "property", value = "facturaCabecera"))
	@Id
	@GeneratedValue(generator = "generator")
	@Column(name = "CAB_NRO_INTERNO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCabNroInterno() {
		return this.cabNroInterno;
	}

	public void setCabNroInterno(long cabNroInterno) {
		this.cabNroInterno = cabNroInterno;
	}

	@OneToOne(fetch = FetchType.LAZY)
	@PrimaryKeyJoinColumn
	public FacturaCabecera getFacturaCabecera() {
		return this.facturaCabecera;
	}

	public void setFacturaCabecera(FacturaCabecera facturaCabecera) {
		this.facturaCabecera = facturaCabecera;
	}

	@Column(name = "TOT_ALICUOTA", precision = 8)
	public BigDecimal getTotAlicuota() {
		return this.totAlicuota;
	}

	public void setTotAlicuota(BigDecimal totAlicuota) {
		this.totAlicuota = totAlicuota;
	}

	@Column(name = "TOT_DESCUENTO", precision = 12)
	public BigDecimal getTotDescuento() {
		return this.totDescuento;
	}

	public void setTotDescuento(BigDecimal totDescuento) {
		this.totDescuento = totDescuento;
	}

	@Column(name = "TOT_EXENTO", precision = 12)
	public BigDecimal getTotExento() {
		return this.totExento;
	}

	public void setTotExento(BigDecimal totExento) {
		this.totExento = totExento;
	}

	@Column(name = "TOT_IMP_LIQUIDADO", precision = 12)
	public BigDecimal getTotImpLiquidado() {
		return this.totImpLiquidado;
	}

	public void setTotImpLiquidado(BigDecimal totImpLiquidado) {
		this.totImpLiquidado = totImpLiquidado;
	}

	@Column(name = "TOT_IMP_RNI", precision = 12)
	public BigDecimal getTotImpRni() {
		return this.totImpRni;
	}

	public void setTotImpRni(BigDecimal totImpRni) {
		this.totImpRni = totImpRni;
	}

	@Column(name = "TOT_IMP_INTERNOS", precision = 12)
	public BigDecimal getTotImpInternos() {
		return this.totImpInternos;
	}

	public void setTotImpInternos(BigDecimal totImpInternos) {
		this.totImpInternos = totImpInternos;
	}

	@Column(name = "TOT_MONTO_IVA", precision = 12)
	public BigDecimal getTotMontoIva() {
		return this.totMontoIva;
	}

	public void setTotMontoIva(BigDecimal totMontoIva) {
		this.totMontoIva = totMontoIva;
	}

	@Column(name = "TOT_NETO_GRAVADO", precision = 12)
	public BigDecimal getTotNetoGravado() {
		return this.totNetoGravado;
	}

	public void setTotNetoGravado(BigDecimal totNetoGravado) {
		this.totNetoGravado = totNetoGravado;
	}

	@Column(name = "TOT_OTROS", precision = 12)
	public BigDecimal getTotOtros() {
		return this.totOtros;
	}

	public void setTotOtros(BigDecimal totOtros) {
		this.totOtros = totOtros;
	}

	@Column(name = "TOT_PERC_ALIC_IIBB", precision = 8)
	public BigDecimal getTotPercAlicIibb() {
		return this.totPercAlicIibb;
	}

	public void setTotPercAlicIibb(BigDecimal totPercAlicIibb) {
		this.totPercAlicIibb = totPercAlicIibb;
	}

	@Column(name = "TOT_PERC_IMPORTE_IIBB", precision = 12)
	public BigDecimal getTotPercImporteIibb() {
		return this.totPercImporteIibb;
	}

	public void setTotPercImporteIibb(BigDecimal totPercImporteIibb) {
		this.totPercImporteIibb = totPercImporteIibb;
	}

	@Column(name = "TOT_PERC_PROV_PERC", length = 15)
	public String getTotPercProvPerc() {
		return this.totPercProvPerc;
	}

	public void setTotPercProvPerc(String totPercProvPerc) {
		this.totPercProvPerc = totPercProvPerc;
	}

	@Column(name = "TOT_PERCEP_MUNICIPAL", precision = 12)
	public BigDecimal getTotPercepMunicipal() {
		return this.totPercepMunicipal;
	}

	public void setTotPercepMunicipal(BigDecimal totPercepMunicipal) {
		this.totPercepMunicipal = totPercepMunicipal;
	}

	@Column(name = "TOT_PERCEPCIONES", precision = 12)
	public BigDecimal getTotPercepciones() {
		return this.totPercepciones;
	}

	public void setTotPercepciones(BigDecimal totPercepciones) {
		this.totPercepciones = totPercepciones;
	}

	@Column(name = "TOT_TOTAL", precision = 12)
	public BigDecimal getTotTotal() {
		return this.totTotal;
	}

	public void setTotTotal(BigDecimal totTotal) {
		this.totTotal = totTotal;
	}

	@Column(name = "TOT_VALOR_PAGAR", precision = 12)
	public BigDecimal getTotValorPagar() {
		return this.totValorPagar;
	}

	public void setTotValorPagar(BigDecimal totValorPagar) {
		this.totValorPagar = totValorPagar;
	}

}
