package ar.com.agromayor.DB.factura;

// Generated Dec 18, 2009 1:30:23 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * FacturaItems generated by hbm2java
 */
@Entity
@Table(name = "FACTURA_ITEMS")
public class FacturaItems implements java.io.Serializable {
	private static final long serialVersionUID = 4988599371792437666L;
	
	private FacturaItemsId id;
	private FacturaCabecera facturaCabecera;
	private BigDecimal detAlicuota;
	private BigDecimal detBonificacion;
	private String detCantidad;
	private String detCodProd;
	private String detDescripcion;
	private BigDecimal detImpuesto;
	private Long detIndicacion;
	private BigDecimal detPrecioNetoUnitario;
	private BigDecimal detPrecioUnitario;
	private BigDecimal detSubTotal;
	private String detUnidadMedida;

	public FacturaItems() {
	}

	public FacturaItems(FacturaItemsId id, FacturaCabecera facturaCabecera) {
		this.id = id;
		this.facturaCabecera = facturaCabecera;
	}

	public FacturaItems(FacturaItemsId id, FacturaCabecera facturaCabecera,
			BigDecimal detAlicuota, BigDecimal detBonificacion,
			String detCantidad, String detCodProd, String detDescripcion,
			BigDecimal detImpuesto, Long detIndicacion,
			BigDecimal detPrecioNetoUnitario, BigDecimal detPrecioUnitario,
			BigDecimal detSubTotal, String detUnidadMedida) {
		this.id = id;
		this.facturaCabecera = facturaCabecera;
		this.detAlicuota = detAlicuota;
		this.detBonificacion = detBonificacion;
		this.detCantidad = detCantidad;
		this.detCodProd = detCodProd;
		this.detDescripcion = detDescripcion;
		this.detImpuesto = detImpuesto;
		this.detIndicacion = detIndicacion;
		this.detPrecioNetoUnitario = detPrecioNetoUnitario;
		this.detPrecioUnitario = detPrecioUnitario;
		this.detSubTotal = detSubTotal;
		this.detUnidadMedida = detUnidadMedida;
	}

	@EmbeddedId
	@AttributeOverrides( {
			@AttributeOverride(name = "cabNroInterno", column = @Column(name = "CAB_NRO_INTERNO", nullable = false, precision = 10, scale = 0)),
			@AttributeOverride(name = "detNumeroItm", column = @Column(name = "DET_NUMERO_ITM", nullable = false, precision = 3, scale = 0)) })
	public FacturaItemsId getId() {
		return this.id;
	}

	public void setId(FacturaItemsId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "CAB_NRO_INTERNO", nullable = false, insertable = false, updatable = false)
	public FacturaCabecera getFacturaCabecera() {
		return this.facturaCabecera;
	}

	public void setFacturaCabecera(FacturaCabecera facturaCabecera) {
		this.facturaCabecera = facturaCabecera;
	}

	@Column(name = "DET_ALICUOTA", precision = 8)
	public BigDecimal getDetAlicuota() {
		return this.detAlicuota;
	}

	public void setDetAlicuota(BigDecimal detAlicuota) {
		this.detAlicuota = detAlicuota;
	}

	@Column(name = "DET_BONIFICACION", precision = 12)
	public BigDecimal getDetBonificacion() {
		return this.detBonificacion;
	}

	public void setDetBonificacion(BigDecimal detBonificacion) {
		this.detBonificacion = detBonificacion;
	}

	@Column(name = "DET_CANTIDAD", length = 45)
	public String getDetCantidad() {
		return this.detCantidad;
	}

	public void setDetCantidad(String detCantidad) {
		this.detCantidad = detCantidad;
	}

	@Column(name = "DET_COD_PROD", length = 20)
	public String getDetCodProd() {
		return this.detCodProd;
	}

	public void setDetCodProd(String detCodProd) {
		this.detCodProd = detCodProd;
	}

	@Column(name = "DET_DESCRIPCION", length = 45)
	public String getDetDescripcion() {
		return this.detDescripcion;
	}

	public void setDetDescripcion(String detDescripcion) {
		this.detDescripcion = detDescripcion;
	}

	@Column(name = "DET_IMPUESTO", precision = 12)
	public BigDecimal getDetImpuesto() {
		return this.detImpuesto;
	}

	public void setDetImpuesto(BigDecimal detImpuesto) {
		this.detImpuesto = detImpuesto;
	}

	@Column(name = "DET_INDICACION", precision = 10, scale = 0)
	public Long getDetIndicacion() {
		return this.detIndicacion;
	}

	public void setDetIndicacion(Long detIndicacion) {
		this.detIndicacion = detIndicacion;
	}

	@Column(name = "DET_PRECIO_NETO_UNITARIO", precision = 12)
	public BigDecimal getDetPrecioNetoUnitario() {
		return this.detPrecioNetoUnitario;
	}

	public void setDetPrecioNetoUnitario(BigDecimal detPrecioNetoUnitario) {
		this.detPrecioNetoUnitario = detPrecioNetoUnitario;
	}

	@Column(name = "DET_PRECIO_UNITARIO", precision = 12)
	public BigDecimal getDetPrecioUnitario() {
		return this.detPrecioUnitario;
	}

	public void setDetPrecioUnitario(BigDecimal detPrecioUnitario) {
		this.detPrecioUnitario = detPrecioUnitario;
	}

	@Column(name = "DET_SUB_TOTAL", precision = 12)
	public BigDecimal getDetSubTotal() {
		return this.detSubTotal;
	}

	public void setDetSubTotal(BigDecimal detSubTotal) {
		this.detSubTotal = detSubTotal;
	}

	@Column(name = "DET_UNIDAD_MEDIDA", length = 10)
	public String getDetUnidadMedida() {
		return this.detUnidadMedida;
	}

	public void setDetUnidadMedida(String detUnidadMedida) {
		this.detUnidadMedida = detUnidadMedida;
	}

}
