package ar.com.agromayor.portal.db;

// Generated Jan 7, 2010 2:27:48 AM by Hibernate Tools 3.2.4.GA

import java.math.BigDecimal;
import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * FacturaCabecera generated by hbm2java
 */
@Entity
@Table(name = "FACTURA_CABECERA")
public class CopyOfFacturaCabecera implements java.io.Serializable {
	private static final long serialVersionUID = 7654143418805054090L;
	
	private long cabNroInterno;
	private Byte emiCodigo;
	private Integer recCodigo;
	private Short recSubcuenta;
	private String cabCodBarras;
	private String cabCondPago;
	private Date cabFechaCpr;
	private Date cabFechaVto;
	private String cabOrigDupli;
	private String cabImprimible;
	private String cabLetra;
	private Long cabLote;
	private Short cabSucursal;
	private Integer cabCprNumero;
	private String cabPeriodoActual;
	private String cabResumenCta;
	private BigDecimal cabSaldoAnterior;
	private String cabTipoCpr;
	private boolean factPdf;
	private String factPdfRuta;
	private String cabCodigoPago1;
	private String cabCodigoPago2;
	private String cabCodigoPago3;
	private String cabCodigoPago4;
	private String cabCodigoPago5;
	private String cabLeyenda1;
	private String cabLeyenda2;
	private String cabLeyenda3;
	private Date cabMesFacturacion;
	private Long cabPublicidad;
	private Byte cabTipoCambio;
	private String cabImporteLetras;
	private String cabCodMoneda;
	private Date cabCuotaMes;
	private String cabCaeCai;
	private Date cabCaeVto;

	public CopyOfFacturaCabecera() {
	}

	public CopyOfFacturaCabecera(long cabNroInterno, boolean factPdf) {
		this.cabNroInterno = cabNroInterno;
		this.factPdf = factPdf;
	}

	public CopyOfFacturaCabecera(long cabNroInterno, Byte emiCodigo,
			Integer recCodigo, Short recSubcuenta, String cabCodBarras,
			String cabCondPago, Date cabFechaCpr, Date cabFechaVto,
			String cabOrigDupli, String cabImprimible, String cabLetra,
			Long cabLote, Short cabSucursal, Integer cabCprNumero,
			String cabPeriodoActual, String cabResumenCta,
			BigDecimal cabSaldoAnterior, String cabTipoCpr, boolean factPdf,
			String factPdfRuta, String cabCodigoPago1, String cabCodigoPago2,
			String cabCodigoPago3, String cabCodigoPago4,
			String cabCodigoPago5, String cabLeyenda1, String cabLeyenda2,
			String cabLeyenda3, Date cabMesFacturacion, Long cabPublicidad,
			Byte cabTipoCambio, String cabImporteLetras, String cabCodMoneda,
			Date cabCuotaMes, String cabCaeCai, Date cabCaeVto) {
		this.cabNroInterno = cabNroInterno;
		this.emiCodigo = emiCodigo;
		this.recCodigo = recCodigo;
		this.recSubcuenta = recSubcuenta;
		this.cabCodBarras = cabCodBarras;
		this.cabCondPago = cabCondPago;
		this.cabFechaCpr = cabFechaCpr;
		this.cabFechaVto = cabFechaVto;
		this.cabOrigDupli = cabOrigDupli;
		this.cabImprimible = cabImprimible;
		this.cabLetra = cabLetra;
		this.cabLote = cabLote;
		this.cabSucursal = cabSucursal;
		this.cabCprNumero = cabCprNumero;
		this.cabPeriodoActual = cabPeriodoActual;
		this.cabResumenCta = cabResumenCta;
		this.cabSaldoAnterior = cabSaldoAnterior;
		this.cabTipoCpr = cabTipoCpr;
		this.factPdf = factPdf;
		this.factPdfRuta = factPdfRuta;
		this.cabCodigoPago1 = cabCodigoPago1;
		this.cabCodigoPago2 = cabCodigoPago2;
		this.cabCodigoPago3 = cabCodigoPago3;
		this.cabCodigoPago4 = cabCodigoPago4;
		this.cabCodigoPago5 = cabCodigoPago5;
		this.cabLeyenda1 = cabLeyenda1;
		this.cabLeyenda2 = cabLeyenda2;
		this.cabLeyenda3 = cabLeyenda3;
		this.cabMesFacturacion = cabMesFacturacion;
		this.cabPublicidad = cabPublicidad;
		this.cabTipoCambio = cabTipoCambio;
		this.cabImporteLetras = cabImporteLetras;
		this.cabCodMoneda = cabCodMoneda;
		this.cabCuotaMes = cabCuotaMes;
		this.cabCaeCai = cabCaeCai;
		this.cabCaeVto = cabCaeVto;
	}

	@Id
	@Column(name = "CAB_NRO_INTERNO", unique = true, nullable = false, precision = 10, scale = 0)
	public long getCabNroInterno() {
		return this.cabNroInterno;
	}

	public void setCabNroInterno(long cabNroInterno) {
		this.cabNroInterno = cabNroInterno;
	}

	@Column(name = "EMI_CODIGO", precision = 2, scale = 0)
	public Byte getEmiCodigo() {
		return this.emiCodigo;
	}

	public void setEmiCodigo(Byte emiCodigo) {
		this.emiCodigo = emiCodigo;
	}

	@Column(name = "REC_CODIGO", precision = 8, scale = 0)
	public Integer getRecCodigo() {
		return this.recCodigo;
	}

	public void setRecCodigo(Integer recCodigo) {
		this.recCodigo = recCodigo;
	}

	@Column(name = "REC_SUBCUENTA", precision = 3, scale = 0)
	public Short getRecSubcuenta() {
		return this.recSubcuenta;
	}

	public void setRecSubcuenta(Short recSubcuenta) {
		this.recSubcuenta = recSubcuenta;
	}

	@Column(name = "CAB_COD_BARRAS", length = 30)
	public String getCabCodBarras() {
		return this.cabCodBarras;
	}

	public void setCabCodBarras(String cabCodBarras) {
		this.cabCodBarras = cabCodBarras;
	}

	@Column(name = "CAB_COND_PAGO", length = 50)
	public String getCabCondPago() {
		return this.cabCondPago;
	}

	public void setCabCondPago(String cabCondPago) {
		this.cabCondPago = cabCondPago;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CAB_FECHA_CPR", length = 7)
	public Date getCabFechaCpr() {
		return this.cabFechaCpr;
	}

	public void setCabFechaCpr(Date cabFechaCpr) {
		this.cabFechaCpr = cabFechaCpr;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CAB_FECHA_VTO", length = 7)
	public Date getCabFechaVto() {
		return this.cabFechaVto;
	}

	public void setCabFechaVto(Date cabFechaVto) {
		this.cabFechaVto = cabFechaVto;
	}

	@Column(name = "CAB_ORIG_DUPLI", length = 20)
	public String getCabOrigDupli() {
		return this.cabOrigDupli;
	}

	public void setCabOrigDupli(String cabOrigDupli) {
		this.cabOrigDupli = cabOrigDupli;
	}

	@Column(name = "CAB_IMPRIMIBLE", length = 5)
	public String getCabImprimible() {
		return this.cabImprimible;
	}

	public void setCabImprimible(String cabImprimible) {
		this.cabImprimible = cabImprimible;
	}

	@Column(name = "CAB_LETRA", length = 1)
	public String getCabLetra() {
		return this.cabLetra;
	}

	public void setCabLetra(String cabLetra) {
		this.cabLetra = cabLetra;
	}

	@Column(name = "CAB_LOTE", precision = 10, scale = 0)
	public Long getCabLote() {
		return this.cabLote;
	}

	public void setCabLote(Long cabLote) {
		this.cabLote = cabLote;
	}

	@Column(name = "CAB_SUCURSAL", precision = 4, scale = 0)
	public Short getCabSucursal() {
		return this.cabSucursal;
	}

	public void setCabSucursal(Short cabSucursal) {
		this.cabSucursal = cabSucursal;
	}

	@Column(name = "CAB_CPR_NUMERO", precision = 8, scale = 0)
	public Integer getCabCprNumero() {
		return this.cabCprNumero;
	}

	public void setCabCprNumero(Integer cabCprNumero) {
		this.cabCprNumero = cabCprNumero;
	}

	@Column(name = "CAB_PERIODO_ACTUAL", length = 10)
	public String getCabPeriodoActual() {
		return this.cabPeriodoActual;
	}

	public void setCabPeriodoActual(String cabPeriodoActual) {
		this.cabPeriodoActual = cabPeriodoActual;
	}

	@Column(name = "CAB_RESUMEN_CTA", length = 10)
	public String getCabResumenCta() {
		return this.cabResumenCta;
	}

	public void setCabResumenCta(String cabResumenCta) {
		this.cabResumenCta = cabResumenCta;
	}

	@Column(name = "CAB_SALDO_ANTERIOR", precision = 10)
	public BigDecimal getCabSaldoAnterior() {
		return this.cabSaldoAnterior;
	}

	public void setCabSaldoAnterior(BigDecimal cabSaldoAnterior) {
		this.cabSaldoAnterior = cabSaldoAnterior;
	}

	@Column(name = "CAB_TIPO_CPR", length = 2)
	public String getCabTipoCpr() {
		return this.cabTipoCpr;
	}

	public void setCabTipoCpr(String cabTipoCpr) {
		this.cabTipoCpr = cabTipoCpr;
	}

	@Column(name = "FACT_PDF", nullable = false, precision = 1, scale = 0)
	public boolean isFactPdf() {
		return this.factPdf;
	}

	public void setFactPdf(boolean factPdf) {
		this.factPdf = factPdf;
	}

	@Column(name = "FACT_PDF_RUTA", length = 500)
	public String getFactPdfRuta() {
		return this.factPdfRuta;
	}

	public void setFactPdfRuta(String factPdfRuta) {
		this.factPdfRuta = factPdfRuta;
	}

	@Column(name = "CAB_CODIGO_PAGO1", length = 70)
	public String getCabCodigoPago1() {
		return this.cabCodigoPago1;
	}

	public void setCabCodigoPago1(String cabCodigoPago1) {
		this.cabCodigoPago1 = cabCodigoPago1;
	}

	@Column(name = "CAB_CODIGO_PAGO2", length = 70)
	public String getCabCodigoPago2() {
		return this.cabCodigoPago2;
	}

	public void setCabCodigoPago2(String cabCodigoPago2) {
		this.cabCodigoPago2 = cabCodigoPago2;
	}

	@Column(name = "CAB_CODIGO_PAGO3", length = 70)
	public String getCabCodigoPago3() {
		return this.cabCodigoPago3;
	}

	public void setCabCodigoPago3(String cabCodigoPago3) {
		this.cabCodigoPago3 = cabCodigoPago3;
	}

	@Column(name = "CAB_CODIGO_PAGO4", length = 70)
	public String getCabCodigoPago4() {
		return this.cabCodigoPago4;
	}

	public void setCabCodigoPago4(String cabCodigoPago4) {
		this.cabCodigoPago4 = cabCodigoPago4;
	}

	@Column(name = "CAB_CODIGO_PAGO5", length = 70)
	public String getCabCodigoPago5() {
		return this.cabCodigoPago5;
	}

	public void setCabCodigoPago5(String cabCodigoPago5) {
		this.cabCodigoPago5 = cabCodigoPago5;
	}

	@Column(name = "CAB_LEYENDA1", length = 70)
	public String getCabLeyenda1() {
		return this.cabLeyenda1;
	}

	public void setCabLeyenda1(String cabLeyenda1) {
		this.cabLeyenda1 = cabLeyenda1;
	}

	@Column(name = "CAB_LEYENDA2", length = 70)
	public String getCabLeyenda2() {
		return this.cabLeyenda2;
	}

	public void setCabLeyenda2(String cabLeyenda2) {
		this.cabLeyenda2 = cabLeyenda2;
	}

	@Column(name = "CAB_LEYENDA3", length = 70)
	public String getCabLeyenda3() {
		return this.cabLeyenda3;
	}

	public void setCabLeyenda3(String cabLeyenda3) {
		this.cabLeyenda3 = cabLeyenda3;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CAB_MES_FACTURACION", length = 7)
	public Date getCabMesFacturacion() {
		return this.cabMesFacturacion;
	}

	public void setCabMesFacturacion(Date cabMesFacturacion) {
		this.cabMesFacturacion = cabMesFacturacion;
	}

	@Column(name = "CAB_PUBLICIDAD", precision = 10, scale = 0)
	public Long getCabPublicidad() {
		return this.cabPublicidad;
	}

	public void setCabPublicidad(Long cabPublicidad) {
		this.cabPublicidad = cabPublicidad;
	}

	@Column(name = "CAB_TIPO_CAMBIO", precision = 2, scale = 0)
	public Byte getCabTipoCambio() {
		return this.cabTipoCambio;
	}

	public void setCabTipoCambio(Byte cabTipoCambio) {
		this.cabTipoCambio = cabTipoCambio;
	}

	@Column(name = "CAB_IMPORTE_LETRAS", length = 70)
	public String getCabImporteLetras() {
		return this.cabImporteLetras;
	}

	public void setCabImporteLetras(String cabImporteLetras) {
		this.cabImporteLetras = cabImporteLetras;
	}

	@Column(name = "CAB_COD_MONEDA", length = 5)
	public String getCabCodMoneda() {
		return this.cabCodMoneda;
	}

	public void setCabCodMoneda(String cabCodMoneda) {
		this.cabCodMoneda = cabCodMoneda;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CAB_CUOTA_MES", length = 7)
	public Date getCabCuotaMes() {
		return this.cabCuotaMes;
	}

	public void setCabCuotaMes(Date cabCuotaMes) {
		this.cabCuotaMes = cabCuotaMes;
	}

	@Column(name = "CAB_CAE_CAI", length = 40)
	public String getCabCaeCai() {
		return this.cabCaeCai;
	}

	public void setCabCaeCai(String cabCaeCai) {
		this.cabCaeCai = cabCaeCai;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "CAB_CAE_VTO", length = 7)
	public Date getCabCaeVto() {
		return this.cabCaeVto;
	}

	public void setCabCaeVto(Date cabCaeVto) {
		this.cabCaeVto = cabCaeVto;
	}

}
